spring:
  application:
    name: opa-decision-log-gateway

server:
  port: 8080

kafka:
  topic:
    decision-logs: decision-logs
  producer:
    acks: all
    retries: 3
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    ai.lab.opa: DEBUG
    org.springframework.kafka: INFO
